name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  lint:
    name: Lint Code with SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  prebuild:
    name: Prebuild Phase
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ticketflow.mindsoftdev.com >> ~/.ssh/known_hosts

      - name: Connect to remote machine and install dependencies
        run: |
          ssh ticketflow@ticketflow.mindsoftdev.com "
            cd /home/ticketflow/htdocs/ticketflow.mindsoftdev.com/project-folder &&
            npm install ||
            (npm audit || true)
          "

  test:
    name: Testing Phase
    runs-on: ubuntu-latest
    needs: prebuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --watch=false

  deploy:
    name: Deploy Phase
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npm run build
