name: SonarQube Cloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para un análisis completo

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Cambia a tu versión de Node.js si es diferente

      - name: Install dependencies
        run: npm install # Cambia a npm install si usas npm

      - name: Build project and generate coverage
        run: |
          npm test --watch=false --code-coverage # Genera la cobertura en la carpeta coverage
          npm run build --prod # Construye el proyecto

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  prebuild-front:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ticketflow
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd htdocs/ticketflow.mindsoftdev.com/ticketflow &&
            git pull origin master &&
            npm install || echo "npm install failed"
            npm audit || echo "npm audit failed" || true
            npm audit fix || echo "npm audit fix failed" || true

  prebuild-back:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: servicios
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd htdocs/servicios.mindsoftdev.com/serviciosTicketFlow/ && composer i && composer u && npm i || npm audit fix

  build-front:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ticketflow
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd htdocs/ticketflow.mindsoftdev.com/ticketflow && npm run build
  
  build-back:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: servicios
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd htdocs/servicios.mindsoftdev.com/serviciosTicketFlow && composer u && composer i && npm run build

  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ticketflow
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd htdocs/ticketflow.mindsoftdev.com/ticketflow && npm test
  
  test-back:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: servicios
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd htdocs/servicios.mindsoftdev.com/serviciosTicketFlow && php artisan test || true
